@echo off
cd /d "C:\Users\Hassa\OneDrive\سطح المكتب\mg-designs-production\interior-design-portfolio"
echo Starting MG Designs Server...
echo Installing dependencies if needed...
call npm install
echo Starting server on port 3003...
node src/server.js
pause
